package suggest

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/jasondillingham/bosun/internal/brief"
)

func init() {
	// Pin the clock for the whole test binary so the date line is stable.
	now = func() time.Time { return time.Date(2026, 5, 16, 0, 0, 0, 0, time.UTC) }
}

func sampleProposal() LaneProposal {
	return LaneProposal{
		Version: "v1",
		Goal:    "Migrate the codebase from React Router v5 to v6",
		Sessions: []Lane{
			{
				Label:      "session-1",
				Scope:      "Introduce a v6 compatibility shim everyone else can lean on",
				OwnedFiles: []string{"src/router-shim/**", "src/router-shim.test.ts"},
				AvoidFiles: []string{"src/pages/**"},
				WorkToDo:   []string{"Add the shim module", "Export the compat types", "Wire the shim into the app entry point"},
				Notes:      "Land first — everyone else depends on you.",
			},
			{
				Label:      "session-2",
				Scope:      "Migrate the /auth routes onto v6",
				OwnedFiles: []string{"src/pages/auth/**"},
				DependsOn:  []string{"session-1"},
				WorkToDo:   []string{"Convert <Switch> to <Routes>", "Update useHistory → useNavigate"},
			},
			{
				Label:      "session-3",
				Scope:      "Migrate the /dashboard routes onto v6",
				OwnedFiles: []string{"src/pages/dashboard/**"},
				DependsOn:  []string{"session-1"},
				WorkToDo:   []string{"Rewrite nested routes"},
			},
			{
				Label:      "session-4",
				Scope:      "Strip the v5 imports once /auth and /dashboard are migrated",
				OwnedFiles: []string{"src/legacy-router-cleanup/**"},
				DependsOn:  []string{"session-2", "session-3"},
				WorkToDo:   []string{"Delete react-router-dom v5 usage", "Bump package.json"},
				Notes:      "Coordinate the package.json bump with infra.",
			},
		},
	}
}

func TestRenderPlanMarkdown_Header(t *testing.T) {
	out := RenderPlanMarkdown(sampleProposal())
	for _, want := range []string{
		"# Plan: Migrate the codebase from React Router v5 to v6\n",
		"Generated by `bosun suggest` on 2026-05-16",
		"bosun init --brief <this-file>",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("header missing %q\n--- output ---\n%s", want, out)
		}
	}
}

func TestRenderPlanMarkdown_LaneSections(t *testing.T) {
	out := RenderPlanMarkdown(sampleProposal())
	for _, want := range []string{
		"## session-1\n",
		"**Introduce a v6 compatibility shim everyone else can lean on**",
		"Work to do:\n- Add the shim module\n- Export the compat types\n",
		"Files (own):\n- src/router-shim/**\n- src/router-shim.test.ts\n",
		"Files (avoid):\n- src/pages/**\n",
		"**Notes:** Land first — everyone else depends on you.",
		"## session-2 (depends: session-1)\n",
		"## session-4 (depends: session-2, session-3)\n",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("output missing %q\n--- output ---\n%s", want, out)
		}
	}
}

func TestRenderPlanMarkdown_OmitsEmptyBlocks(t *testing.T) {
	proposal := LaneProposal{
		Goal:     "tiny goal",
		Sessions: []Lane{{Label: "session-1", Scope: "do a thing"}},
	}
	out := RenderPlanMarkdown(proposal)
	for _, unwanted := range []string{
		"Work to do:",
		"Files (own):",
		"Files (avoid):",
		"**Notes:**",
		"(depends:",
	} {
		if strings.Contains(out, unwanted) {
			t.Errorf("output should not contain %q for an empty-field lane\n--- output ---\n%s", unwanted, out)
		}
	}
	if !strings.Contains(out, "## session-1\n") {
		t.Errorf("expected bare `## session-1` heading without depends clause:\n%s", out)
	}
	if !strings.Contains(out, "**do a thing**") {
		t.Errorf("scope still rendered:\n%s", out)
	}
}

func TestRenderPlanMarkdown_EmptyGoalIsPlaceholder(t *testing.T) {
	out := RenderPlanMarkdown(LaneProposal{Sessions: []Lane{{Label: "session-1", Scope: "x"}}})
	if !strings.Contains(out, "# Plan: (no goal provided)") {
		t.Errorf("empty goal should fall back to placeholder:\n%s", out)
	}
}

func TestRenderPlanMarkdown_SequencingNotesTopoOrdered(t *testing.T) {
	out := RenderPlanMarkdown(sampleProposal())
	if !strings.Contains(out, "## Sequencing notes\n") {
		t.Fatalf("missing 'Sequencing notes' footer:\n%s", out)
	}

	// session-1 has no deps; session-2 + session-3 depend on session-1;
	// session-4 depends on session-2 + session-3. Topo order must put
	// session-1 first and session-4 last.
	footer := out[strings.Index(out, "## Sequencing notes"):]
	lines := []string{
		"- session-1 — Introduce a v6 compatibility shim",
		"- session-2 (after session-1) — Migrate the /auth routes",
		"- session-3 (after session-1) — Migrate the /dashboard routes",
		"- session-4 (after session-2, session-3) — Strip the v5 imports",
	}
	last := -1
	for _, want := range lines {
		idx := strings.Index(footer, want)
		if idx < 0 {
			t.Errorf("sequencing notes missing line %q\n--- footer ---\n%s", want, footer)
			continue
		}
		if idx <= last {
			t.Errorf("sequencing notes out of topo order — %q appeared before previous line\n--- footer ---\n%s", want, footer)
		}
		last = idx
	}
}

func TestRenderPlanMarkdown_SequencingNotesNotParsedAsLane(t *testing.T) {
	// The footer heading must not pass brief.Parse's `## [a-z]…` regex,
	// or round-trip tests would see N+1 briefs instead of N.
	out := RenderPlanMarkdown(sampleProposal())
	path := writeTemp(t, out)
	briefs, err := brief.Parse(path)
	if err != nil {
		t.Fatalf("brief.Parse(%s): %v", path, err)
	}
	for _, b := range briefs {
		if strings.HasPrefix(b.Label, "sequencing") || b.Label == "sequencing-notes" {
			t.Errorf("sequencing footer parsed as a lane: %+v", b)
		}
	}
}

func TestRenderPlanMarkdown_RoundTripThroughBriefParse(t *testing.T) {
	cases := []struct {
		name     string
		proposal LaneProposal
	}{
		{"react-router fixture", sampleProposal()},
		{
			name: "single lane no deps",
			proposal: LaneProposal{
				Goal:     "one shot",
				Sessions: []Lane{{Label: "session-1", Scope: "do it", WorkToDo: []string{"step 1"}}},
			},
		},
		{
			name: "named labels with deps",
			proposal: LaneProposal{
				Goal: "named-label run",
				Sessions: []Lane{
					{Label: "storage", Scope: "lift storage"},
					{Label: "http", Scope: "wire http", DependsOn: []string{"storage"}},
					{Label: "auth", Scope: "auth on top", DependsOn: []string{"storage", "http"}},
				},
			},
		},
		{
			name: "chain of numeric deps",
			proposal: LaneProposal{
				Goal: "long chain",
				Sessions: []Lane{
					{Label: "session-1", Scope: "first"},
					{Label: "session-2", Scope: "second", DependsOn: []string{"session-1"}},
					{Label: "session-3", Scope: "third", DependsOn: []string{"session-2"}},
				},
			},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			out := RenderPlanMarkdown(tc.proposal)
			path := writeTemp(t, out)

			briefs, err := brief.Parse(path)
			if err != nil {
				t.Fatalf("brief.Parse: %v\n--- markdown ---\n%s", err, out)
			}

			if len(briefs) != len(tc.proposal.Sessions) {
				t.Fatalf("session count mismatch: got %d briefs, want %d\n--- markdown ---\n%s",
					len(briefs), len(tc.proposal.Sessions), out)
			}

			for i, lane := range tc.proposal.Sessions {
				if briefs[i].Label != lane.Label {
					t.Errorf("brief[%d].Label = %q, want %q", i, briefs[i].Label, lane.Label)
				}
				if !equalStrings(briefs[i].Depends, lane.DependsOn) {
					t.Errorf("brief[%d].Depends = %v, want %v", i, briefs[i].Depends, lane.DependsOn)
				}
			}
		})
	}
}

func TestRenderPlanMarkdown_BodySurvivesRoundTrip(t *testing.T) {
	// The brief body fed to each agent is the markdown between its
	// heading and the next heading. Verify the per-lane content
	// (scope, work-to-do, owned files) lands in the right brief body
	// and not someone else's.
	proposal := sampleProposal()
	out := RenderPlanMarkdown(proposal)
	path := writeTemp(t, out)

	briefs, err := brief.Parse(path)
	if err != nil {
		t.Fatalf("brief.Parse: %v", err)
	}

	want := map[string][]string{
		"session-1": {
			"Introduce a v6 compatibility shim",
			"Add the shim module",
			"src/router-shim/**",
			"Land first",
		},
		"session-2": {
			"Migrate the /auth routes onto v6",
			"Convert <Switch> to <Routes>",
			"src/pages/auth/**",
		},
		"session-4": {
			"Strip the v5 imports",
			"Bump package.json",
			"Coordinate the package.json bump",
		},
	}

	for _, b := range briefs {
		checks, ok := want[b.Label]
		if !ok {
			continue
		}
		for _, fragment := range checks {
			if !strings.Contains(b.Body, fragment) {
				t.Errorf("brief %q body missing %q\n--- body ---\n%s", b.Label, fragment, b.Body)
			}
		}
	}
}

func TestRenderPlanMarkdown_BodyDoesNotLeakAcrossLanes(t *testing.T) {
	// Regression guard: brief.Parse splits on headings, so a missing
	// trailing separator could let one lane's content end up appended
	// to the previous lane's body.
	proposal := sampleProposal()
	out := RenderPlanMarkdown(proposal)
	path := writeTemp(t, out)

	briefs, err := brief.Parse(path)
	if err != nil {
		t.Fatalf("brief.Parse: %v", err)
	}
	first := lookupBriefBody(briefs, "session-1")
	for _, leak := range []string{
		"Migrate the /auth routes onto v6",
		"src/pages/auth/**",
		"Strip the v5 imports",
	} {
		if strings.Contains(first, leak) {
			t.Errorf("session-1 body unexpectedly contains content from a later lane: %q\n--- body ---\n%s", leak, first)
		}
	}
}

func TestTopoSort_StableTieBreak(t *testing.T) {
	lanes := []Lane{
		{Label: "session-1"},
		{Label: "session-2"},
		{Label: "session-3"},
		{Label: "session-4", DependsOn: []string{"session-1", "session-2", "session-3"}},
	}
	got := topoSort(lanes)
	wantOrder := []string{"session-1", "session-2", "session-3", "session-4"}
	for i, lane := range got {
		if lane.Label != wantOrder[i] {
			t.Errorf("topo[%d] = %q, want %q (full order: %v)", i, lane.Label, wantOrder[i], labelsOf(got))
		}
	}
}

func TestTopoSort_HandlesCycleGracefully(t *testing.T) {
	// If the validator misses a cycle, we don't want the renderer to
	// crash or silently drop lanes. Every input label must appear in
	// the output.
	lanes := []Lane{
		{Label: "a", DependsOn: []string{"b"}},
		{Label: "b", DependsOn: []string{"a"}},
		{Label: "c"},
	}
	got := topoSort(lanes)
	if len(got) != 3 {
		t.Fatalf("topoSort dropped lanes on cycle: %v", labelsOf(got))
	}
	seen := map[string]bool{}
	for _, lane := range got {
		seen[lane.Label] = true
	}
	for _, want := range []string{"a", "b", "c"} {
		if !seen[want] {
			t.Errorf("topoSort missing label %q after cycle fallback: %v", want, labelsOf(got))
		}
	}
}

func writeTemp(t *testing.T, contents string) string {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, "plan.md")
	if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
		t.Fatalf("write plan: %v", err)
	}
	return path
}

func lookupBriefBody(briefs []brief.Brief, label string) string {
	for _, b := range briefs {
		if b.Label == label {
			return b.Body
		}
	}
	return ""
}

func equalStrings(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func labelsOf(lanes []Lane) []string {
	out := make([]string, len(lanes))
	for i, lane := range lanes {
		out[i] = lane.Label
	}
	return out
}
