package suggest

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

// LaneProposal is the structured output of the proposer — N lanes the
// operator can review then turn into a plan markdown.
//
// These types mirror the shared contract spelled out in
// `v0.5-round1-plan.md`. They live here so this lane can compile
// independently; the round's lane-1 owns `internal/suggest/types.go` and
// is expected to lift these declarations there. When that lands, remove
// the duplicates here.
type LaneProposal struct {
	Version  string `json:"version"`
	Goal     string `json:"goal"`
	Sessions []Lane `json:"sessions"`
}

// Lane is one proposed session in a LaneProposal.
type Lane struct {
	Label      string   `json:"label"`
	Scope      string   `json:"scope"`
	OwnedFiles []string `json:"owned_files"`
	AvoidFiles []string `json:"avoid_files"`
	DependsOn  []string `json:"depends_on"`
	Rationale  string   `json:"rationale"`
	WorkToDo   []string `json:"work_to_do"`
	Notes      string   `json:"notes"`
}

// now is the clock used by RenderPlanMarkdown. Tests swap it to keep
// the generated-date line deterministic without having to massage the
// rendered output.
var now = func() time.Time { return time.Now() }

// RenderPlanMarkdown converts a LaneProposal into the plan-markdown
// format `bosun init --brief` consumes. The output:
//
//   - Starts with `# Plan: <goal>` and a one-paragraph banner naming
//     `bosun suggest` + the generation date.
//   - Renders one `## <label>` section per lane, with the optional
//     `(depends: …)` clause brief.Parse already recognises, the scope
//     in bold, and Work-to-do / Files (own) / Files (avoid) / Notes
//     sub-blocks. Sections are omitted entirely when their field is
//     empty so we don't litter the file with blank stubs the operator
//     has to clean up.
//   - Ends with a "Sequencing notes" footer that lists every lane in
//     topological order — operator-facing breadcrumb so they can sanity
//     check the dep graph before kickoff. The heading deliberately
//     starts with a capital letter so brief.Parse's `[a-z]…` label
//     regex ignores it and the round-trip session count stays right.
func RenderPlanMarkdown(proposal LaneProposal) string {
	var b strings.Builder

	goal := strings.TrimSpace(proposal.Goal)
	if goal == "" {
		goal = "(no goal provided)"
	}
	fmt.Fprintf(&b, "# Plan: %s\n\n", goal)
	fmt.Fprintf(&b,
		"Generated by `bosun suggest` on %s. Review and edit before\n"+
			"running `bosun init --brief <this-file>`.\n\n",
		now().UTC().Format("2006-01-02"))
	b.WriteString("---\n\n")

	for _, lane := range proposal.Sessions {
		renderLane(&b, lane)
	}

	renderSequencingNotes(&b, proposal.Sessions)
	return b.String()
}

func renderLane(b *strings.Builder, lane Lane) {
	heading := "## " + lane.Label
	if len(lane.DependsOn) > 0 {
		heading += " (depends: " + strings.Join(lane.DependsOn, ", ") + ")"
	}
	b.WriteString(heading + "\n\n")

	if scope := strings.TrimSpace(lane.Scope); scope != "" {
		fmt.Fprintf(b, "**%s**\n\n", scope)
	}

	if len(lane.WorkToDo) > 0 {
		b.WriteString("Work to do:\n")
		for _, item := range lane.WorkToDo {
			fmt.Fprintf(b, "- %s\n", item)
		}
		b.WriteString("\n")
	}

	if len(lane.OwnedFiles) > 0 {
		b.WriteString("Files (own):\n")
		for _, p := range lane.OwnedFiles {
			fmt.Fprintf(b, "- %s\n", p)
		}
		b.WriteString("\n")
	}

	if len(lane.AvoidFiles) > 0 {
		b.WriteString("Files (avoid):\n")
		for _, p := range lane.AvoidFiles {
			fmt.Fprintf(b, "- %s\n", p)
		}
		b.WriteString("\n")
	}

	if notes := strings.TrimSpace(lane.Notes); notes != "" {
		fmt.Fprintf(b, "**Notes:** %s\n\n", notes)
	}

	b.WriteString("---\n\n")
}

func renderSequencingNotes(b *strings.Builder, lanes []Lane) {
	if len(lanes) == 0 {
		return
	}
	b.WriteString("## Sequencing notes\n\n")
	b.WriteString("Dependency graph (topo-ordered):\n\n")

	for _, lane := range topoSort(lanes) {
		scope := strings.TrimSpace(lane.Scope)
		switch {
		case len(lane.DependsOn) > 0 && scope != "":
			fmt.Fprintf(b, "- %s (after %s) — %s\n",
				lane.Label, strings.Join(lane.DependsOn, ", "), scope)
		case len(lane.DependsOn) > 0:
			fmt.Fprintf(b, "- %s (after %s)\n",
				lane.Label, strings.Join(lane.DependsOn, ", "))
		case scope != "":
			fmt.Fprintf(b, "- %s — %s\n", lane.Label, scope)
		default:
			fmt.Fprintf(b, "- %s\n", lane.Label)
		}
	}
	b.WriteString("\n")
}

// topoSort returns lanes ordered so every lane appears after the lanes
// it depends on (Kahn's algorithm). Ties are broken by the lane's
// original index so the output is stable across runs.
//
// On a dependency cycle (which the validator package should reject
// upstream), any lanes that don't drain are appended in input order so
// the footer still mentions every lane rather than silently dropping
// the cyclic subgraph.
func topoSort(lanes []Lane) []Lane {
	byLabel := make(map[string]Lane, len(lanes))
	inDeg := make(map[string]int, len(lanes))
	indexOf := make(map[string]int, len(lanes))
	children := make(map[string][]string, len(lanes))
	for i, lane := range lanes {
		byLabel[lane.Label] = lane
		inDeg[lane.Label] = 0
		indexOf[lane.Label] = i
	}
	for _, lane := range lanes {
		for _, dep := range lane.DependsOn {
			if _, ok := byLabel[dep]; !ok {
				continue
			}
			inDeg[lane.Label]++
			children[dep] = append(children[dep], lane.Label)
		}
	}

	var ready []string
	for label, deg := range inDeg {
		if deg == 0 {
			ready = append(ready, label)
		}
	}
	sort.Slice(ready, func(i, j int) bool { return indexOf[ready[i]] < indexOf[ready[j]] })

	out := make([]Lane, 0, len(lanes))
	seen := make(map[string]bool, len(lanes))
	for len(ready) > 0 {
		label := ready[0]
		ready = ready[1:]
		out = append(out, byLabel[label])
		seen[label] = true

		var next []string
		for _, child := range children[label] {
			inDeg[child]--
			if inDeg[child] == 0 {
				next = append(next, child)
			}
		}
		sort.Slice(next, func(i, j int) bool { return indexOf[next[i]] < indexOf[next[j]] })
		ready = append(ready, next...)
	}

	for _, lane := range lanes {
		if !seen[lane.Label] {
			out = append(out, lane)
		}
	}
	return out
}
